### PR TITLE
Support setup.cfg

### PR DESCRIPTION
**Pull request by kxepal**

### CODE REVIEW

**Comment by kxepal** [comment]
Tests failures here are about Pipfile feature /:

**Comment by jayfk** [comment]
Thanks a bunch for that!

**Comment by jayfk** [comment]
> Tests failures here are about Pipfile feature /:

Yep, tracking that here: https://github.com/pyupio/dparse/issues/19

**Comment by keimlink** [comment]
@kxepal Thank you for implementing this! 👍 

@jayfk Is this a feature considered stable? We received a ton of new PRs to pin dependencies from the bot. If it's stable it should be mentioned in the docs. 😃

**Comment by kxepal** [comment]
@keimlink :tada: 
I wouldn't say this feature is very stable since it's only one week old (: Time will tell.  If you'll found any bugs or missing parts of that feature feel free to report back and ping me. But so far it should works fine and as expected.

**Comment by keimlink** [comment]
Great. I'll test it with one of our projects that is already using a `setup.cfg` to declare it's dependencies.

**Pull request merged**
